language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t alexbudy/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alexbudy/react-test npm test

after_success:
  - docker build -t alexbudy/multi-client ./client 
  - docker build -t alexbudy/multi-nginx ./nginx 
  - docker build -t alexbudy/multi-server ./server
  - docker build -t alexbudy/multi-worker ./worker
  # log in to CLI:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push alexbudy/multi-client
  - docker push alexbudy/multi-nginx
  - docker push alexbudy/multi-server
  - docker push alexbudy/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-445673876924'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
